### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by avram** [OniDaito/ZotDroid#11]
Nice work!

What license is this under?

**Comment by avram** [comment]
Given that the history [pretty clearly](https://github.com/OniDaito/ZotDroid/commit/c6bb79735b70fd909a15a96db48387e7a027922b) has Zandy code in it, the only license you can provide it under is AGPLv3. Happy to see you make good use of the existing functionality to make something better-- but make sure you respect the license on the software.

**Comment by OniDaito** [comment]
Hello there. Not sure yet. Although I started with the Zandy code, it's moved quite far since then. For now I'm happy to add the AGPLv3. I've often used the GNU Public licence in the past. I'll add that in the next version though I suspect the Zandy code will be totally removed before release.

**Comment by avram** [comment]
To clarify, if you started with AGPL code and made a sequence of changes that removed those lines while reworking the implementation, the derived product is, to best of my understanding of the license, still a derivative of the original AGPL-licensed code, and you are obligated to provide it under the AGPL as well.

**Comment by avram** [comment]
Thanks for clarifying the license!
