### ISSUE TITLE
Back arrow not doing anything in Settings

### ISSUE THREAD

**Issue by techexo** [OniDaito/ZotDroid#6]
Hi

First, thank you for your work. Even in early development, it is more promising that all the others app not taking into account the people using WebDav! This is great and I am looking forward to see the developments of the app.

Going into Settings > General then clicking the back arrow (in the top ribbon) works as intended.

However, clicking in the first level of Settings on the back arrow doesn't exit the settings to go back on the Zotero library (tapping the phone back button works).

Cheers

**Comment by OniDaito** [comment]
I did originally have a problem that sounds like this one, however, I can't seem to reproduce this in the current build.

**Comment by techexo** [comment]
Indeed it seems to be solved :smiley:

**Comment by OniDaito** [comment]
Good good.

**Comment by OniDaito** [comment]
Re-opening because for some reason, on a different device test, the last arrow press does not go back to the main activity. :S

**Comment by OniDaito** [comment]
Seems to only occur on certain devices. Might be an API issue

**Comment by techexo** [comment]
I confirm that on a OnePlus3t the problem is still present.
