### ISSUE TITLE
Cancel button not displayed in landscape mode

### ISSUE THREAD

**Issue by techexo** [OniDaito/ZotDroid#8]
Hi

When using ZotDroid on a smartphone running Android Nougat (LineageOS), the cancel button is not displayed in landscape mode.

This happens for example when testing (and failing) WebDav connection, or when an error is displayed for not finding a file.

Regards

**Comment by OniDaito** [comment]
Interesting, I only use landscape mode. I'll need to have a think about this one, and try a few things out in the next version.

**Comment by OniDaito** [comment]
Hopefully this should be fixed now that I've properly resized the dialog boxes.
